### ISSUE TITLE
HEX/Keymap for the Xenon?

### ISSUE THREAD

**Issue by Kyrremann** [narinari/xenon-keyboard#1]
I've ordered my own Xenon, and started building it, but can't find the keymap for it. Have you made one to share, or should I create my own?

Also, have you thought about making a build guide? I'm taking pictures while I'm building it, but don't have the best camera setup for a proper guide.

**Comment by Kyrremann** [comment]
I've made my own now, and I'll soon create a PR for qmk, just need to test the OLED
https://github.com/Kyrremann/qmk_firmware/tree/xenon/keyboards/xenon

All credits to you, but used my name in the license, as it felt strange to put your name there without your acknowledge. Let me know what you'd like.

**Comment by molohov** [comment]
> I've made my own now, and I'll soon create a PR for qmk, just need to test the OLED https://github.com/Kyrremann/qmk_firmware/tree/xenon/keyboards/xenon
> 
> All credits to you, but used my name in the license, as it felt strange to put your name there without your acknowledge. Let me know what you'd like.

THANK YOU for sharing this!

**Comment by ifohancroft** [comment]
Sorry to hijack the issue but where's the OLED on the keyboard? I can't see it on any of the pictures.

**Comment by Kyrremann** [comment]
It's right over the Pro Micro, but it's in none of the pictures. Similar style as [Corne](https://github.com/foostan/crkbd).

**Comment by ifohancroft** [comment]
Thank you!

**Comment by ifohancroft** [comment]
Can you tell me what model OLED screen supports so I can buy it for my Xenon?
Also the readme says it supports full color LEDs - I presume this means RGB? However, is it underglow or is it per key? Any specific model? I couldn't figure it out looking at the KiCad files as the schematic symbols library is missing from the repo

**Comment by Kyrremann** [comment]
About the OLED, you can read the technical know-how over at [QMK](https://docs.qmk.fm/#/feature_oled_driver). The short answer is any OLED that support SSD1306 or SH1106, and fits the case. 

You should find them if you search for 0.91 inch OLED. They look like this:
![OLED for keebs](https://img.joomcdn.net/421e37b9ff96512d2873a643a1dee8409965bb4c_original.jpeg)

Not sure about the LEDS, I see that there is support for LED-strips, so my guess is that's all there is.

**Comment by ifohancroft** [comment]
Thank you!
Do you happen to know if the acrylic cover comes with the OLED module or what are its dimensions?

The case, I presume is just the bottom plate and you mount the plate, pcb and bottom plate? Also what size standoffs?

I was gifted the Xenon with everything (including keycaps and switches) but there is no bottom plate and the repo doesn't include a build guide, so I don't know what I'm missing.

**Comment by Kyrremann** [comment]
You have to cut your own OLED acrylic cover, bottom plate, and switch plate. I used this file to do it: https://github.com/narinari/xenon-keyboard/blob/master/xenon-e/cad-data/xenon-e_plate.svg
I think I use regular 8mm stand-offs, but it may be 6mm.

It sounds like your missing the case (not really necessary to use it), screws, standoffs/spacers, OLED, Pro Micro, TRRS-cable between the splits, and a usb-micro cable (for the Pro Micro).

**Comment by ifohancroft** [comment]
Thank you!

When you say case? Do you mean the bottom plate?

Sorry, I didn't clarify well what I have. I have: PCBs, Switch plates, Pro Micros (with USB-C), Hotswap sockets, diodes, rotary encoders, rotary encoder caps, switches, choch switches, keycaps and chock keycaps.

So, I guess I am missing the following: Case (or bottom plate, not sure if they are the same thing or if there is an actual case that is different from the bottom plate), screws, standoffs/spacers, OLEDs, TRRS-cable and USB cable.

P.S. How thick of an acrylic sheet did you use for the cover?
How did you secure the cover/to what? I.e. do you glue it to the OLED or screw it to the PCB or to the bottom plate?

**Comment by Kyrremann** [comment]
When I said case I meant all the acrylic, but sounds like you are only missing a bottom plate. Not really necessary, but nice to have.

I sued 2mm acrylic for bottom plate and OLED cover. And used 10mm standoff to screw it on. It's not currently set up like that, but I can try to take a picture later today.
It's identical to this: https://github.com/foostan/crkbd/blob/main/corne-classic/doc/buildguide_en.md#oled-module

Are the USB-C Pro Micros Elite-C?

**Comment by ifohancroft** [comment]
Ah! Got it. Thank you! If you can take a picture later, that would be extremely helpful.

Do you know if I need a diode on the rotary encoder? I mean if I use a rotary encoder instead of a switch below the X key on the pictures?

Honestly, I have no idea if they are Elite-C. They don't look like the Elite-C and the PCB is blue. On one side 'Pro Micro' is printed on the board. On the other 'Atmega 32u4'. I don't think they are.

Btw myy switch plate is from FR-4, so I'm considering getting a bottom plate made from it as well.

**Comment by Kyrremann** [comment]
The firmware is now merged into master!
https://github.com/qmk/qmk_firmware/tree/master/keyboards/xenon

Closing this issue now.

**Comment by Kyrremann** [comment]
I'm guessing this is the Pro Micro you https://www.sparkfun.com/products/15795 (or at least a clone of it).

Not sure if you need a diode, I soldered one there.

FR-4 cases are nice, and yeah, making it the same style as the switch plate is a good choice.

I couldn't find the OLED cover for my Xenon, but it look's just like the one for Corne.

**Comment by ifohancroft** [comment]
Thank you!
